name: Test list-seqs tool

on: [push]

jobs:
  testing:
    name: Test list-seqs tool
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Building project
        uses: ./.github/actions/build

      - name: Running test
        run:  ./test-list-seqs.sh
        shell: bash
